M48
; DRILL file {KiCad (6.0.9)} date Mon Nov 21 21:05:14 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-21T21:05:14-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.6207Y-1.9307
X3.6207Y-5.5607
X7.0207Y-1.9307
X7.0207Y-5.5607
T0
M30
