M48
; DRILL file {KiCad (6.0.2)} date Sun Nov  6 15:29:17 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-06T15:29:17-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.6207Y-1.9307
X3.6207Y-5.5607
X7.0207Y-1.9307
X7.0207Y-5.5607
T0
M30
