M48
; DRILL file {KiCad (6.0.2)} date Sun Nov  6 15:02:34 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-06T15:02:34-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.18Y-1.985
X4.18Y-5.615
X7.58Y-1.985
X7.58Y-5.615
T0
M30
