M48
; DRILL file {KiCad (6.0.9)} date Mon Nov 21 20:51:04 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-21T20:51:04-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.9776Y-1.9713
X3.9776Y-5.3713
X7.6076Y-1.9713
X7.6076Y-5.3713
T0
M30
